version: "3.8"

services:
  backend:
    container_name: iris-llm-backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always

  frontend:
    container_name: iris-llm-frontend
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - backend
